### ISSUE TITLE
Не запускается аадон

### ISSUE THREAD

**Issue by ruspray** [aatrubilin/hassio-torrserver#15]
После нажатия на кнопку запуска сразу останавливается 
в логе написано: /run.sh: line 45: /share/torrserver/TorrServer-MatriX.132: Permission denied

**Comment by aatrubilin** [comment]
Привет. 
1. Скинь скриншот версии HA, доступен на странице: `http[s]://<your-ha-isntance>/config/info`

<details>
<summary>Пример версии</summary>

<img width="619" alt="image" src="https://github.com/aatrubilin/hassio-torrserver/assets/29011393/1ad2378f-d765-44e7-94df-b10d20c85f21">
</details>

2. Лог supervisor после запуска аддона
    Настройки -> Система -> Журнал сервера -> в правом верхнем углу выбрать Supervisor
    `http[s]://<your-ha-isntance>/config/logs?provider=supervisor`

**Comment by ruspray** [comment]
![image](https://github.com/aatrubilin/hassio-torrserver/assets/22346816/f4e779a9-1c7f-458b-a7f7-f7d71f40104c)

лог сразу после запуска
2024-04-15 18:58:38.122 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_31a3518e_torrserver application
2024-04-15 18:58:38.560 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 31a3518e/amd64-addon-torrserver with version 0.2.14

**Comment by arsenal3008** [comment]
Удалил, скачал версию с обновленными 
Dockerfile и run.sh
Теперь пишет:
2024-04-16 15:22:03.256 ERROR (SyncWorker_1) [supervisor.docker.manager] Container addon_93d47a47_torrserver is not running
2024-04-16 15:22:03.259 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-25595' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1418> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1432, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 290, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-04-16 15:22:05.901 ERROR (SyncWorker_0) [supervisor.docker.manager] Container addon_93d47a47_torrserver is not running

**Comment by OlegMoshin** [comment]
2024-04-16 20:46:19.163 ERROR (SyncWorker_7) [supervisor.docker.manager] Container addon_31a3518e_torrserver is not running
<img width="618" alt="Снимок экрана 2024-04-16 в 20 42 44" src="https://github.com/aatrubilin/hassio-torrserver/assets/145882892/6f002614-b114-40d2-b555-874d3d103fbc">

**Comment by aatrubilin** [comment]
Не могу у себя воспроизвести. версии такие-же.

1. Удалите аддон
2. Установите заново
3. Запустите аддон

Киньте или полный лог supervisor или начиная с сообщений об удалении аддон, у меня это выглядит примерно так:

```
2024-04-17 16:32:14.316 INFO (SyncWorker_1) [supervisor.docker.manager] Stopping addon_31a3518e_torrserver application
2024-04-17 16:32:17.625 INFO (SyncWorker_1) [supervisor.docker.manager] Cleaning addon_31a3518e_torrserver application
2024-04-17 16:32:17.670 INFO (SyncWorker_6) [supervisor.docker.manager] Removing image 31a3518e/amd64-addon-torrserver with latest
2024-04-17 16:32:17.679 INFO (SyncWorker_6) [supervisor.docker.manager] Removing image 31a3518e/amd64-addon-torrserver with 0.2.14
2024-04-17 16:32:17.798 INFO (MainThread) [supervisor.addons.addon] Removing add-on data folder /data/addons/data/31a3518e_torrserver
2024-04-17 16:32:17.908 INFO (MainThread) [supervisor.host.apparmor] Removing AppArmor profile: 31a3518e_torrserver
2024-04-17 16:32:17.951 INFO (MainThread) [supervisor.addons.manager] Add-on '31a3518e_torrserver' successfully removed
2024-04-17 16:32:24.753 INFO (MainThread) [supervisor.addons.addon] Creating Home Assistant add-on data folder /data/addons/data/31a3518e_torrserver
2024-04-17 16:32:24.762 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: 31a3518e_torrserver
2024-04-17 16:32:24.857 INFO (MainThread) [supervisor.docker.addon] Starting build for 31a3518e/amd64-addon-torrserver:0.2.14
2024-04-17 16:32:36.513 INFO (MainThread) [supervisor.docker.addon] Build 31a3518e/amd64-addon-torrserver:0.2.14 done
2024-04-17 16:32:36.515 INFO (MainThread) [supervisor.addons.manager] Add-on '31a3518e_torrserver' successfully installed
2024-04-17 16:33:14.545 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 31a3518e/amd64-addon-torrserver with version 0.2.14

```

**Comment by arsenal3008** [comment]
2024-04-17 12:42:19.715 INFO (SyncWorker_1) [supervisor.docker.manager] Removing image 93d47a47/aarch64-addon-torrserver with latest
2024-04-17 12:42:19.724 INFO (SyncWorker_1) [supervisor.docker.manager] Removing image 93d47a47/aarch64-addon-torrserver with 0.2.14
2024-04-17 12:42:19.950 INFO (MainThread) [supervisor.addons.addon] Removing add-on data folder /data/addons/data/93d47a47_torrserver
2024-04-17 12:42:20.105 INFO (MainThread) [supervisor.host.apparmor] Removing AppArmor profile: 93d47a47_torrserver
2024-04-17 12:42:20.142 INFO (MainThread) [supervisor.addons.manager] Add-on '93d47a47_torrserver' successfully removed
2024-04-17 12:42:56.513 INFO (MainThread) [supervisor.addons.addon] Creating Home Assistant add-on data folder /data/addons/data/93d47a47_torrserver
2024-04-17 12:42:56.523 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: 93d47a47_torrserver
2024-04-17 12:42:56.640 INFO (MainThread) [supervisor.docker.addon] Starting build for 93d47a47/aarch64-addon-torrserver:0.2.14
2024-04-17 12:43:18.176 INFO (MainThread) [supervisor.docker.addon] Build 93d47a47/aarch64-addon-torrserver:0.2.14 done
2024-04-17 12:43:18.177 INFO (MainThread) [supervisor.addons.manager] Add-on '93d47a47_torrserver' successfully installed
2024-04-17 12:43:24.814 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 93d47a47/aarch64-addon-torrserver with version 0.2.14
2024-04-17 12:46:12.228 INFO (SyncWorker_0) [supervisor.docker.manager] Cleaning addon_93d47a47_torrserver application
2024-04-17 12:46:13.145 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 93d47a47/aarch64-addon-torrserver with version 0.2.14
2024-04-17 12:46:20.196 ERROR (SyncWorker_4) [supervisor.docker.manager] Container addon_93d47a47_torrserver is not running

**Comment by OlegMoshin** [comment]
2024-04-17 13:22:17.610 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_31a3518e_torrserver application
2024-04-17 13:22:17.640 INFO (SyncWorker_4) [supervisor.docker.manager] Removing image 31a3518e/aarch64-addon-torrserver with latest
2024-04-17 13:22:17.644 INFO (SyncWorker_4) [supervisor.docker.manager] Removing image 31a3518e/aarch64-addon-torrserver with 0.2.14
2024-04-17 13:22:17.699 INFO (MainThread) [supervisor.addons.addon] Removing add-on data folder /data/addons/data/31a3518e_torrserver
2024-04-17 13:22:17.745 INFO (MainThread) [supervisor.host.apparmor] Removing AppArmor profile: 31a3518e_torrserver
2024-04-17 13:22:17.762 INFO (MainThread) [supervisor.addons.manager] Add-on '31a3518e_torrserver' successfully removed
2024-04-17 13:22:58.890 INFO (MainThread) [supervisor.addons.addon] Creating Home Assistant add-on data folder /data/addons/data/31a3518e_torrserver
2024-04-17 13:22:58.893 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: 31a3518e_torrserver
2024-04-17 13:22:58.930 INFO (MainThread) [supervisor.docker.addon] Starting build for 31a3518e/aarch64-addon-torrserver:0.2.14
2024-04-17 13:23:15.484 INFO (MainThread) [supervisor.docker.addon] Build 31a3518e/aarch64-addon-torrserver:0.2.14 done
2024-04-17 13:23:15.484 INFO (MainThread) [supervisor.addons.manager] Add-on '31a3518e_torrserver' successfully installed
2024-04-17 13:23:23.564 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 31a3518e/aarch64-addon-torrserver with version 0.2.14
2024-04-17 13:24:03.629 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_31a3518e_torrserver application
2024-04-17 13:24:04.222 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 31a3518e/aarch64-addon-torrserver with version 0.2.14
2024-04-17 13:25:23.112 INFO (SyncWorker_1) [supervisor.docker.manager] Cleaning addon_31a3518e_torrserver application
2024-04-17 13:25:23.690 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 31a3518e/aarch64-addon-torrserver with version 0.2.14
2024-04-17 13:25:27.918 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon TorrServer is failed, restarting...
2024-04-17 13:25:27.926 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_31a3518e_torrserver application
2024-04-17 13:25:28.550 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 31a3518e/aarch64-addon-torrserver with version 0.2.14
2024-04-17 13:25:32.527 ERROR (SyncWorker_0) [supervisor.docker.manager] Container addon_31a3518e_torrserver is not running
2024-04-17 13:25:32.533 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon TorrServer is failed, restarting...
2024-04-17 13:25:32.538 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_31a3518e_torrserver application
2024-04-17 13:25:33.152 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 31a3518e/aarch64-addon-torrserver with version 0.2.14
2024-04-17 13:25:34.825 INFO (SyncWorker_4) [supervisor.docker.manager] Stopping addon_31a3518e_torrserver application
2024-04-17 13:25:37.122 INFO (SyncWorker_4) [supervisor.docker.manager] Cleaning addon_31a3518e_torrserver application
2024-04-17 13:25:37.728 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 31a3518e/aarch64-addon-torrserver with version 0.2.14
2024-04-17 13:25:41.672 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon TorrServer is failed, restarting...
2024-04-17 13:25:41.677 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_31a3518e_torrserver application
2024-04-17 13:25:42.273 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 31a3518e/aarch64-addon-torrserver with version 0.2.14
2024-04-17 13:25:46.246 ERROR (SyncWorker_6) [supervisor.docker.manager] Container addon_31a3518e_torrserver is not running
2024-04-17 13:25:46.251 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon TorrServer is failed, restarting...
2024-04-17 13:25:46.257 INFO (SyncWorker_7) [supervisor.docker.manager] Cleaning addon_31a3518e_torrserver application
2024-04-17 13:25:46.879 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 31a3518e/aarch64-addon-torrserver with version 0.2.14
2024-04-17 13:25:50.821 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon TorrServer is failed, restarting...
2024-04-17 13:25:50.826 INFO (SyncWorker_7) [supervisor.docker.manager] Cleaning addon_31a3518e_torrserver application
2024-04-17 13:25:51.422 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 31a3518e/aarch64-addon-torrserver with version 0.2.14
2024-04-17 13:25:55.366 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon TorrServer is failed, restarting...
2024-04-17 13:25:55.372 INFO (SyncWorker_7) [supervisor.docker.manager] Cleaning addon_31a3518e_torrserver application
2024-04-17 13:25:55.982 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 31a3518e/aarch64-addon-torrserver with version 0.2.14
2024-04-17 13:25:59.927 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon TorrServer is failed, restarting...
2024-04-17 13:25:59.932 INFO (SyncWorker_7) [supervisor.docker.manager] Cleaning addon_31a3518e_torrserver application
2024-04-17 13:26:00.583 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 31a3518e/aarch64-addon-torrserver with version 0.2.14
2024-04-17 13:26:04.545 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon TorrServer is failed, restarting...
2024-04-17 13:26:04.550 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_31a3518e_torrserver application
2024-04-17 13:26:05.179 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 31a3518e/aarch64-addon-torrserver with version 0.2.14
2024-04-17 13:26:09.126 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon TorrServer is failed, restarting...
2024-04-17 13:26:09.132 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_31a3518e_torrserver application
2024-04-17 13:26:09.722 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 31a3518e/aarch64-addon-torrserver with version 0.2.14
2024-04-17 13:26:13.697 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon TorrServer is failed, restarting...
2024-04-17 13:26:13.703 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_31a3518e_torrserver application
2024-04-17 13:26:14.304 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 31a3518e/aarch64-addon-torrserver with version 0.2.14
2024-04-17 13:26:18.260 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-19990' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1418> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1432, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 290, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00

**Comment by OlegMoshin** [comment]
Raspberry Pi 5
rpi5-64

**Comment by aatrubilin** [comment]
А можете еще скинуть логи самого аддона? 

<img width="1078" alt="image" src="https://github.com/aatrubilin/hassio-torrserver/assets/29011393/f4a7daea-8167-4a13-b33c-c93629ddad3b">

**Comment by aatrubilin** [comment]
по вашим логам вроде билдится аддон успешно и запускается, но дальше возникают проблемы с запуском. 

Возможно там будет опять что-то подобное `/run.sh: line 45: /share/torrserver/TorrServer-MatriX.132: Permission denied`

**Comment by OlegMoshin** [comment]
<img width="1054" alt="Снимок экрана 2024-04-17 в 14 36 26" src="https://github.com/aatrubilin/hassio-torrserver/assets/145882892/d98c82bc-a41b-4321-beb8-894900b48fe8">

**Comment by aatrubilin** [comment]
@OlegMoshin попробуй версию 0.2.15 - должно помочь.

Если не запустится - скинь также свежий лог аддона

**Comment by arsenal3008** [comment]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Build arch: aarch64
TS_SOURCE=TorrServer-linux-arm64
TS_URL=https://github.com/YouROK/TorrServer/releases/latest/download/TorrServer-linux-arm64
TS_VERSION=MatriX.132
TS_RUNFILE=/share/torrserver/TorrServer-MatriX.132
Checking existed torrserver
Change mode
Starting TorrServer-MatriX.132...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by arsenal3008** [comment]
2024-04-17 14:50:03.801 INFO (MainThread) [supervisor.addons.addon] Creating Home Assistant add-on data folder /data/addons/data/93d47a47_torrserver
2024-04-17 14:50:03.809 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: 93d47a47_torrserver
2024-04-17 14:50:03.910 INFO (MainThread) [supervisor.docker.addon] Starting build for 93d47a47/aarch64-addon-torrserver:0.2.15
2024-04-17 14:50:28.653 INFO (MainThread) [supervisor.docker.addon] Build 93d47a47/aarch64-addon-torrserver:0.2.15 done
2024-04-17 14:50:28.654 INFO (MainThread) [supervisor.addons.manager] Add-on '93d47a47_torrserver' successfully installed
2024-04-17 14:50:43.093 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
2024-04-17 14:50:46.277 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 93d47a47/aarch64-addon-torrserver with version 0.2.15
2024-04-17 14:53:00.227 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-04-17 14:53:26.142 INFO (SyncWorker_7) [supervisor.docker.manager] Cleaning addon_93d47a47_torrserver application
2024-04-17 14:53:27.122 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on 93d47a47/aarch64-addon-torrserver with version 0.2.15
2024-04-17 14:53:27.839 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
2024-04-17 14:53:27.850 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/matt8707/addon-ha-fusion repository
2024-04-17 14:53:27.857 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/dfigus/hassio-addons repository
2024-04-17 14:53:27.864 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
2024-04-17 14:53:27.872 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
2024-04-17 14:53:27.885 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
2024-04-17 14:53:27.895 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/aatrubilin/hassio-torrserver/ repository
2024-04-17 14:53:30.473 INFO (MainThread) [supervisor.store] Loading add-ons from store: 80 all - 0 new - 0 remove
2024-04-17 14:53:30.473 INFO (MainThread) [supervisor.store] Loading add-ons from store: 80 all - 0 new - 0 remove
2024-04-17 14:53:32.110 ERROR (SyncWorker_3) [supervisor.docker.manager] Container addon_93d47a47_torrserver is not running
2024-04-17 14:54:17.531 ERROR (SyncWorker_5) [supervisor.docker.manager] Container addon_93d47a47_torrserver is not running

**Comment by OlegMoshin** [comment]
![Uploading Снимок экрана 2024-04-17 в 14.58.07.png…]()

**Comment by OlegMoshin** [comment]
<img width="1042" alt="Снимок экрана 2024-04-17 в 14 58 07" src="https://github.com/aatrubilin/hassio-torrserver/assets/145882892/c1602d85-b8d5-4efe-96e1-be6f250dc37b">

**Comment by aatrubilin** [comment]
Пока нет догадок:(

Возможно что arm64 образ torrserver не запускается на aarch64 архитектуре rpi.

Как будет возможность - запущу ha у себя на rpi, попробую локально воспроизвести, подебажить. 

Отпишусь по результатам

**Comment by OlegMoshin** [comment]
Спасибо, предыдущая версия работала исправно. Будем ждать

**Comment by aatrubilin** [comment]
@OlegMoshin так, если прошлая версия работала - то есть еще одна догадка.

Попробуй 0.2.16

**Comment by OlegMoshin** [comment]
<img width="1042" alt="Снимок экрана 2024-04-17 в 18 00 50" src="https://github.com/aatrubilin/hassio-torrserver/assets/145882892/0ba362d6-4a75-4757-b7a9-c7472aee645f">

на сколько помню работала 0.2.7

**Comment by aatrubilin** [comment]
@OlegMoshin привет!
попробуй 0.2.17

**Comment by aatrubilin** [comment]
@ruspray варианты есть, со временем тяжко

**Comment by OlegMoshin** [comment]
0.2.17 всё тоже самое, останавливается. Ждем обновления, спасибо🙂

**Comment by aatrubilin** [comment]
@OlegMoshin странно, в 0.2.17 откатил все к 0.2.7.

Попробую совсем другой подход, отпишусь как будет готово

**Comment by aatrubilin** [comment]
Какая-то магия, я установить ha на свою rpi, правда версии 3b+. Но архитектура такая-же (aarch64), аддон запустился без проблем.

<img width="961" alt="image" src="https://github.com/aatrubilin/hassio-torrserver/assets/29011393/952ad5e1-b3bf-458e-9663-1d07edbb4dd5">


<img width="624" alt="image" src="https://github.com/aatrubilin/hassio-torrserver/assets/29011393/8df38c06-d8a7-46c1-853d-3a39d528b007">

Только версия haos отличается, сейчас обновлю и проверю еще финально

**Comment by aatrubilin** [comment]
В последней версии haos тоже запускается без проблем..

@OlegMoshin @ruspray @arsenal3008 может кто-нибудь дать доступ в свой ha - в веб? 

Можно в личку написать - https://t.me/aatrubilin

**Comment by aatrubilin** [comment]
Всем у кого возникла эта ошибка - зайдите через terminal в ha, например через аддон https://github.com/home-assistant/addons/tree/master/ssh, удалите файл `/share/torrserver/TorrServer-*`, например `/share/torrserver/TorrServer-MatriX.132` и перезапустите аддон - должно быть ок
